// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pin-item'
  | 'pin-items'
  | 'pinitems-column-name'
  | 'pref-pinitems-sort-order-ascending'
  | 'pref-pinitems-sort-order-descending'
  | 'pref-pinitems-sort-order-description'
  | 'pref-pinitems-sort-order-files-after'
  | 'pref-pinitems-sort-order-files-before'
  | 'pref-pinitems-sort-order-files-description'
  | 'pref-pinitems-sort-order-files-title'
  | 'pref-pinitems-sort-order-title'
  | 'pref-title'
  | 'unpin-item'
  | 'unpin-items';
